### ISSUE TITLE
Diagramme FAST

### ISSUE THREAD

**Issue by MaximeBelcour** [Little-Groundhog/Insic-Cuisine#3]

**Comment by MaximeBelcour** [comment]
@AdrienNebon Sur le FP1 j'ai rajouté une colonne pour répondre à la solution de la problématique avant la réponse technique en bleu. Comme on avait fait sur le cahier des charges en analyse fonctionnelle l'an dernier. Tu en penses quoi ? On fait comme ça sur tous ?

**Comment by AdrienNebon** [comment]
Yes c'est vrai que c'est mieux comme ça t'a raison. Je pense qu'on peut le faire sur tous

**Comment by MaximeBelcour** [comment]
Pour FC17 (respecter les normes) je ne vois pas comment on peut faire le fast 🤔
