### ISSUE TITLE
Définir les paramètres pour chaque modules

### ISSUE THREAD

**Issue by MaximeBelcour** [Little-Groundhog/Insic-Cuisine#7]
- Faire un tableau avec les différentes possibilités de paramétrage pour chaque modules.

- Détailler comment on peut réaliser notre conception évolutive avec une mise en place automatique des meubles dans la cuisine.

**Comment by MaximeBelcour** [comment]
J'ai fait un premier tableau pour le placard haut vous en pensez quoi ? 
![image](https://user-images.githubusercontent.com/22176758/93851693-e1258e80-fcb0-11ea-9765-255f0d92866d.png)

**Comment by MaximeBelcour** [comment]
n'hésitez pas à changer les couleurs je viens de me rendre compte qu'elles sont dégelasses je les ai fait sur un écran à lumière jaune, c'était pas prévu que ça rende comme ça

**Comment by MaximeBelcour** [comment]
Pour l'emplacement des éléments dans le système je ne sais pas comment définir l'emplacement de chaque module par rapport aux autres. 
Actuellement je suis parti sur un système de référence par modules pour définir sa configuration mais le problème est que si j'inscrit dedans la position relative du module par rapport aux autres ça fait une référence trop grosse.

Voici le plan de travail bas par exemple : (pas encore terminée)
![image](https://user-images.githubusercontent.com/22176758/93883992-9886c900-fce2-11ea-86ce-3d4b5a02945a.png)

Comment dire dans la référence qu'il est entre le frigo et l'évier ? 

Solutions possibles : 

- sur 4 caractères prendre les 2 lettres des modules l'encadrant et si le modules et le premier ou le dernier 00 pour premier FF pour dernier (codage en hexa plus simple à traiter en VBA ensuite).

- Définir un numéro d'emplacement auto incrémental en fonction de l'emplacement choisi par l'utilisateur sur une plan vue dessus sur le site web.

- Faire des emplacements automatique et on shoot le problème de choix de l'emplacement par l'utilisateur.

**Comment by MaximeBelcour** [comment]
Pour l'évier on le créer comme un meuble entier qui va prendre une place entière entre deux meubles ou on le place sur un plan de travail en prenant de la place sur celui ci ? 
Afin de savoir si on fait un paramètre pour choisir sur quel meuble placer l'évier parmi ceux disponibles :octocat:

**Comment by AdrienNebon** [comment]
Pour le frigo et le four je pense que c'est la meilleure solution.
Pour l'évier, à mon avis c'est mieux de le créer comme un meuble entier, parce que quand il y en a un, tout l'agencement du meuble est affectée, en particulier la taille et la place sous l'évier.
