### ISSUE TITLE
Etude de marché

### ISSUE THREAD

**Issue by MaximeBelcour** [Little-Groundhog/Insic-Cuisine#8]

**Comment by MaximeBelcour** [comment]
Les avantages de la configuration 3D est vide et l'analyse de la concurrence il y a une image. L'issue sur Github est fermé c'est normal ?
![image](https://user-images.githubusercontent.com/22176758/93877668-0e863280-fcd9-11ea-9f82-ec716d3bc18e.png)

**Comment by charlottejnk** [comment]
J'avais zappé les avantages mais tu me diras ce que tu en penses et si tu as des choses à rajouter ou même Adrien parce que je vois pas ce que je pourrais rajouter de plus.

**Comment by MaximeBelcour** [comment]
t'inquiètes 😉 ça marche je vais regarder ça merci :octocat:
